services:
  hls-origin:
    network_mode: "container:gluetun-torrent"
    ports: !reset []

  kick-output:
    network_mode: "container:gluetun-torrent"
    environment:
      LOCAL_HLS_URL: "${LOCAL_HLS_URL_GLUETUN_NAMESPACE:-http://127.0.0.1/live/index.m3u8}"
